# Test Script for Blynk Extension
# This is a sample MicroPython code that should be generated by MicroBlock

import blynklib_mp as blynklib

# Initialize Blynk with enhanced options
blynk = blynklib.Blynk("YourAuthTokenHere", server="blynk.cloud", port=80, heartbeat_timeout=30, firmware_version="2.0.0")

# Set template information
blynk.template_id = "TMPL000000"
blynk.device_name = "Test Device"

# Send firmware info
blynk.firmware_info("2.0.0")

@blynk.handle_event("read V1")
def blynk_read_v1(pin):
    # Send sensor data when app requests it
    blynk.virtual_write(pin, 25.5)

@blynk.handle_event("write V2")  
def blynk_write_v2(pin, values):
    # Handle data from app
    led_state = int(values[0])
    print("LED state:", led_state)

@blynk.handle_event("connect")
def blynk_on_connect():
    print("Connected to Blynk!")
    # Sync virtual pins on connect
    blynk.sync_virtual(1)

@blynk.handle_event("disconnect")
def blynk_on_disconnect():
    print("Disconnected from Blynk!")

# Example of using new features
def send_batch_data():
    blynk.batch_send_start()
    blynk.virtual_write(1, 25.5)  # Temperature
    blynk.virtual_write(2, 60.2)  # Humidity  
    blynk.virtual_write(3, 1013.2)  # Pressure
    blynk.batch_send_end()

def update_widget_properties():
    # Update button color
    blynk.update_property(2, "color", "#FF0000")
    # Update label
    blynk.set_property(3, "label", "Temperature: 25.5°C")

# Main loop - this should run continuously  
def main():
    import time
    
    while True:
        try:
            blynk.run()  # Process Blynk messages
            
            # Send data periodically (every 10 seconds)
            if int(time.time()) % 10 == 0:
                send_batch_data()
                update_widget_properties()
                
        except Exception as e:
            print("Error:", e)
            
        time.sleep(0.1)  # Small delay to prevent busy waiting

if __name__ == "__main__":
    print("Starting Blynk test...")
    main()